fix(OU-467): refactor and simplify panel logic to fix races
openshift/troubleshooting-panel-console-plugin pull request #38
Opened 2024-07-09 21:06 UTC by alanconway

See https://issues.redhat.com/browse/OU-476
Repeating the same query gave different results, sometimes success, sometimes a JSON parsing error.

Refactored Korrle8rPanel logic to simplify and remove race conditions:

- No props passed to Korrle8rPanel, initialize from context URL.
- useState only for query and result, no redux or dispatch. There is no need to share state with other components.
- Single atomic state variable for result: holds graph or error.
- Don't check other plugin availability, let korrel8r determine what is available at runtime.
- Don't filter results, assume korrel8r will return correct results.
- Always run query even if it hasn't changed - simpler logic + the cluster state may have changed.

2024-07-09 21:08 UTC, alanconway commented
This is a pure refactor to simplify the code and remove races. I'll rebase my other PRs on this so please take a look @PeterYurkovich

2024-07-09 22:00 UTC, PeterYurkovich requested changes
Thank you for the refactor, everything feels a lot cleaner this way. However, the check for the logging plugin and the netflow plugin will likely need to be added back. Although korrel8r checks if the infrastructure exists, AFAIK korrel8r doesn't check if the console plugins exist. These plugins can be turned on and off separate from loki, and even if someone has loki and logging enabled, we shouldn't show the nodes unless the links will work.

Alternatively korrel8r could check if the plugins are enabled, but that seems like it would be outside of what it is trying to do

2024-07-09 22:02 UTC, PeterYurkovich commented on web/src/components/Korrel8rPanel.tsx
> +  }, [result, query, t]);
This was referring to the topology function, but the changes under it moved the line number down

2024-07-09 22:09 UTC, PeterYurkovich commented on web/src/components/Korrel8rPanel.tsx
> +    if (result != null) {
Javascript has a lot of weird and very specific oddities with comparisons especially with null. Both this comparison and the one in the topology function should use the triple equal checks to ensure that only null is matched, `!==` and `===` respectively

2024-07-10 07:09 UTC, jgbernalp commented on web/src/components/Korrel8rPanel.tsx
> +    null as { graph?: Korrel8rGraphNeighboursResponse; message?: string; title?: string },
```suggestion
  const [result, setResult] = React.useState< { graph?: Korrel8rGraphNeighboursResponse; message?: string; title?: string } | null>(
    null
```

2024-07-10 15:34 UTC, alanconway commented
Re checking for plugins: I think we should enable korrel8r and show results even if console plugins are missing,
and then grey out any nodes in the result that cannot be mapped to a console URL as a result. So the check still belongs in the console, but moves to the URL mapping logic instead of the enable/disable of korrel8r as a whole.
Korrel8r is intended to be open ended, and should be able to display partial results even if some components are missing - e.g. lack of netobserve should not prevent showing logging results and vice versa - but we should grey out netobserv odes in the result if we can't create a working URL because there's no netobserv plugin.

2024-07-10 16:01 UTC, PeterYurkovich commented
I think the largest issue with moving the logic to the URL mapping would be that the status of the other plugins would need to be rechecked in a number of different places, rather than just one. For example, the topology view performs a URL mapping to check if the current URL matches the Korrel8r query of a node, and then highlights that node if it does. 

I think the purpose of the toURL, fromURL and related functions should be pure and not dependent on whether a plugin exists or not. The expected URL should always be the expected URL, even if it doesn't go anywhere.

One thing I think we can do is to move the check further down the component tree, rather than doing it right when the fetch call happens. We can put it in the new `topology` component you are creating, return the loading state while the checks are going on, then either pass the status down to the `Korrel8rTopology` file or perform the filter there. There isn't really a need to wait for the checks to happen before making the query to korrel8r, we just need to make sure the checks are done before we leave the loading state

2024-07-10 16:04 UTC, alanconway commented on web/src/components/Korrel8rPanel.tsx
> +  }, [result, query, t]);
I think t has to be passed, the use*** hooks are only supposed to be called at the top of a component function.

2024-07-10 16:08 UTC, alanconway commented
+1 - probably belongs in the node display logic. My main concern is the check should govern how nodes are displayed (greyed out or whatever) not cause the entire panel to be disabled. I'll write an issue for that so we can fix it later.

2024-07-10 16:08 UTC, PeterYurkovich commented
As far as making the nodes grayed out rather than hidden, I think it could help show the benefits of utilizing those other plugins and shouldn't cause any visual clutter, so it seems like a good idea. I do think that it exceeds the purpose of a refactor though, and should maybe be moved out into a separate PR.

2024-07-10 16:14 UTC, PeterYurkovich commented on web/src/components/Korrel8rPanel.tsx
> +  }, [result, query, t]);
The `topology` function is acting as a component function and can be converted into one

2024-07-10 16:16 UTC, alanconway commented
@PeterYurkovich Fixed all comments I think, will add a new issue for displaying nodes with missing plugins.

2024-07-10 16:23 UTC, alanconway commented
https://github.com/openshift/troubleshooting-panel-console-plugin/issues/39

2024-07-10 17:47 UTC, PeterYurkovich requested changes
One final change, but looks good outside of that

2024-07-10 18:15 UTC, PeterYurkovich commented
/lgtm

2024-07-10 18:20 UTC, merged