OU-378: Add a Go Backend
openshift/troubleshooting-panel-console-plugin pull request #9
Opened 2024-05-09 18:57 UTC by PeterYurkovich

This PR adds a go backend to the Troubleshooting Panel, updates documentation and the helm charts for deployment

2024-05-09 19:05 UTC, PeterYurkovich commented
/jira refresh

2024-05-09 20:41 UTC, zhuje commented on Makefile
> +.PHONY: install-frontend-ci-clean
I think you might need to add `install-frontend-ci` in this make command: 

```
.PHONY: install-frontend-ci-clean
install-frontend-ci-clean: install-frontend-ci
	cd web && npm cache clean --force
```

2024-05-09 20:41 UTC, zhuje commented on Makefile
> +.PHONY: install-frontend-ci-clean
See logging-view-plugin for reference: https://github.com/openshift/logging-view-plugin/blob/c15865761f06c4e081e51be7477287cbcfd4508a/Makefile#L11C1-L13C35

2024-05-13 08:31 UTC, jgbernalp requested changes

2024-05-13 08:31 UTC, jgbernalp commented on README.md
> +5. `go run ./cmd/plugin-backend.go -port='9002' -config-path='./web/dist' -static-path='./web/dist'`
maybe it will be better to point to the makefile commands, which may already install dependencies as dependent commands

2024-05-13 08:31 UTC, jgbernalp commented on charts/openshift-console-plugin/templates/configmap.yaml
> +    logsLimit: 100
We don't have logs limit for now in this plugin

```suggestion
```

2024-05-13 08:31 UTC, jgbernalp commented on pkg/server.go
> +	LogsLimit                       int           `json:"logsLimit,omitempty" yaml:"logsLimit,omitempty"`
Maybe we should clean this up and add the ones we expect for this plugin only

2024-05-14 12:56 UTC, jgbernalp commented
LGTM

2024-05-14 12:56 UTC, merged